service: stackoverflow_clone

image: amsak701/stclone

servers:
  web:
    - 89.23.97.92

# Credentials for your image host (Docker Hub).
registry:
  username: amsak701
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: "1"
    RAILS_SERVE_STATIC_FILES: "true"
    SOLID_QUEUE_IN_PUMA: "true"
    WEB_CONCURRENCY: "2"
    RAILS_MAX_THREADS: "5"
    REDIS_URL: redis://redis:6379/0
    ELASTICSEARCH_URL: http://elasticsearch:9200

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "stackoverflow_clone_storage:/rails/storage"
  - "stackoverflow_clone_log:/rails/log"
  - "stackoverflow_clone_tmp:/rails/tmp"

asset_path: /rails/public/assets

builder:
  arch: amd64



accessories:
  redis:
    image: redis:7-alpine
    host: 89.23.97.92
    port: "127.0.0.1:6379:6379"
    directories:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    host: 89.23.97.92
    port: "127.0.0.1:9200:9200"
    env:
      clear:
        discovery.type: single-node
        xpack.security.enabled: "false"
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    directories:
      - es-data:/usr/share/elasticsearch/data
